.travis.yml, README.md, appveyor.yml
=> Appveyor & Travis CI integration

package.json, quickstart/src/index.js
=> Fix Issue #9

.gitignore, CHANGELOG.md, README.md, examples/localvideosnapshot/public/index.css, examples/localvideosnapshot/public/index.html, examples/localvideosnapshot/public/prism.css, examples/localvideosnapshot/src/helpers.js, examples/localvideosnapshot/src/index.js, package.json, server/index.js
@markandrus 
Let me know what you think.
=> JSDK-1280 Local video snapshot example.

.gitignore, CHANGELOG.md, README.md, examples/localvideofilter/public/index.css, examples/localvideofilter/public/index.html, examples/localvideofilter/public/prism.css, examples/localvideofilter/src/filters.js, examples/localvideofilter/src/helpers.js, examples/localvideofilter/src/index.js, examples/mediadevices/public/index.html, package.json, server/index.js
@markandrus ,
This is the PR for the Local Video Filter example. I also alphabetized the examples in this PR.
Let me know what you think.
My next PR will be about refactoring based on your suggestions.
=> JSDK-1281 Local Video Filter example.

README.md, examples/bandwidthconstraints/src/index.js, examples/codecpreferences/public/index.html, examples/codecpreferences/src/index.js, package.json, quickstart/src/index.js
=> JSDK-1973 Updating twilio-video.js to 2.x.

server/index.js
=> Setting ttl to 4 hours.

.gitignore, examples/index.html, examples/screenshare/public/index.css, examples/screenshare/public/index.html, examples/screenshare/public/prism.css, examples/screenshare/src/helpers.js, examples/screenshare/src/index.js, package.json, server/index.js
@syerrapragada , @makarandp0 ,
This example app demonstrates how to create a LocalVideoTrack for your screen using `getDisplayMedia()`. This is how the app looks:
=> JSDK-2353 Adding an example for capturing screen using getDisplayMedia().

.gitignore, examples/dominantspeaker/public/index.css, examples/dominantspeaker/public/index.html, examples/dominantspeaker/public/prism.css, examples/dominantspeaker/src/helpers.js, examples/dominantspeaker/src/index.js, examples/index.html, examples/util/getroomcredentials.js, package.json, server/index.js
@manjeshbhargav, @syerrapragada,
This sample app demonstrates usage of `dominantSpeakerChanged` event on the `Room`. The app creates a room w/o media and lets user add participants in the room.
It listens for `participantConnected` event and as participant join it renders their media. It also listens for `dominantSpeakerChanged` event and renders dominantSpeaker's media prominently.
=> JSDK-2354 - quickstart sample to demonstrate dominant speaker detection

package.json
=> Pin latest release version until 2.0 GA

examples/index.html, quickstart/public/index.css, quickstart/public/index.html
Added a link to navigate from quick-start to examples and another to navigate from examples back to the quick-start.
=> Added links to navigate between quick-start and example pages

examples/index.html, quickstart/public/index.css, quickstart/public/index.html
Added link to examples from the quickstart and to the quickstart from the examples
=> added links to examples and quickstart

package.json
=> update to twilio-video@1.20.0

package.json
small change to update to latest sdk.
=> update to beta15

quickstart/public/index.css, quickstart/public/index.html
Added text to the quick start to indicate this is the 1.x branch. Also added recommendation and link to 2.x
- [X ] I acknowledge that all my contributions will be made under the project's license.
=> Added text to quickstart to indicate 1.x branch is in use

package.json
updates twilio-video dependency to 2.0.0
=> update to twilio-video@2.0.0

README.md
=> Adding link to best practices guide.

examples/util/waveform.js
Bug fix to check for browser compatibility for AudioContext APIs.
=> JSDK-2482- AudioContext Fix

package.json, quickstart/src/index.js
=> Demonstrating the usage of the isSupported flag.

examples/mediadevices/src/helpers.js
=> Fix deviceId accessor in mediadevices example

examples/mediadevices/src/helpers.js, examples/mediadevices/src/index.js, package.json
[JIRA Ticket](https://issues.corp.twilio.com/browse/JSDK-2911)
This PR is for updating the Media Devices example to use the latest SDK track.restart method. 
=> JSDK-2911 Update MediaDevices example to use track.restart

examples/localvideosnapshot/public/index.css, examples/localvideosnapshot/public/index.html, examples/localvideosnapshot/src/helpers.js, examples/localvideosnapshot/src/index.js
JIRA Ticket : [VIDEO-3928](https://issues.corp.twilio.com/browse/VIDEO-3928)
This PR adds a small fix to the Local Video Snapshot example. I have integrated Charlie's suggested fix to utilize the ImageCapture API.
Here is a demo: [Demo](https://f346a9178a82.ngrok.io)
=> VIDEO-3928 Fix LocalVideoSnapshot
